### ISSUE TITLE
Cannot find module 'typescript'

### ISSUE THREAD

**Issue by saikatkoley** [patilankita79/WeatherApp#1]
[app-scripts]     throw err;
[app-scripts]     ^
[app-scripts] Error: Cannot find module 'typescript'
[app-scripts]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
[app-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:535:25)
[app-scripts]     at Module.require (internal/modules/cjs/loader.js:663:17)
[app-scripts]     at require (internal/modules/cjs/helpers.js:20:18)
[app-scripts]     at Object.<anonymous> (C:\ionicproject\weatherapp\node_modules\@ionic\app-scripts\dist\logger\logger-typescript.js:6:10)
[app-scripts]     at Module._compile (internal/modules/cjs/loader.js:734:30)
[app-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
[app-scripts]     at Module.load (internal/modules/cjs/loader.js:626:32)
[app-scripts]     at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
[app-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:558:3)

**Comment by ravi-pandit14** [comment]
Can we implement this with oneSignal notification
